### ISSUE TITLE
[Feature Request]: Calorie Tracker 

### ISSUE THREAD

**Issue by justhappyuknow** [Open-Code-Crafters/FitFlex#244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

We can add a calorie tracker or can add a feature that tells about BMI and also tells about which food contains what nutritions, I have implemented this in one of my projects so it would be good to have this here as well. 

### Use Case

This feature would increase customer engagement and user interaction on the website.

### Benefits

We can engage people and get the registration data for users who will be using this feature on our site.

### Add ScreenShots

<img width="910" alt="image" src="https://github.com/user-attachments/assets/6e0674b1-d161-4074-b9ae-98e69374bdf3">

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [ ] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by GAVINESHWAR** [comment]
@justhappyuknow, I think someone is is working on it please very it once

**Comment by justhappyuknow** [comment]
> @justhappyuknow, I think someone is is working on it please very it once

I have seen the issues I have seen a diet plan but no such thing as calorie tracker. Please see if you can assign this to me.

**Comment by GAVINESHWAR** [comment]
@justhappyuknow, ok go ahead and on which page this will going to be added.

**Comment by justhappyuknow** [comment]
> @justhappyuknow, ok go ahead and on which page this will going to be added.

If it feels right we can make a new route link in navbar for this or I can add it above footer on homepage itself.

**Comment by GAVINESHWAR** [comment]
@justhappyuknow, add it above the footer and try to finish it as soon as possible.

**Comment by GAVINESHWAR** [comment]
@justhappyuknow, add the changes photos at the submission of PR.

**Comment by justhappyuknow** [comment]
> @justhappyuknow, add it above the footer and try to finish it as soon as possible.

Ok thank you so much, will do asap
