### ISSUE TITLE
[Bug]: Calorie tracker not working

### ISSUE THREAD

**Issue by shamvrueth** [Open-Code-Crafters/FitFlex#376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The calorie tracker section in the home page always shows error fetching data even for valid inputs.

### Expected behavior

It should provide the correct outputs

### Add ScreenShots

![image](https://github.com/user-attachments/assets/8255a20d-2455-49e8-9ee3-0e6fdde4f7e6)

### On which device are you experiencing this bug?

Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [ ] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository
