### ISSUE TITLE
[Feature Request]: Add Missing Meta Tags, robots.txt, sitemaps for SEO Enhancement

### ISSUE THREAD

**Issue by myselfshivams** [Open-Code-Crafters/FitFlex#395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The current project lacks essential meta tags that are crucial for search engine optimization (SEO). To improve the visibility and ranking of the website on search engines

### Use Case

we need to add the following missing meta tags:

Title tags
Description tags
Keywords tags
Open Graph tags for social media sharing
Robots meta tag

### Benefits

SEO Enhancement, search engine can crawl easily

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [ ] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository
