### ISSUE TITLE
[Bug]: Calorie Tracker is not working 

### ISSUE THREAD

**Issue by things12** [Open-Code-Crafters/FitFlex#428]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

While going to the task bar of the calorie tracker it was showing while fetching the data.

### Expected behavior

fetching file should be  connected to the html page. 

### Add ScreenShots

<img width="884" alt="Screenshot 2024-11-05 204020" src="https://github.com/user-attachments/assets/c10cedc5-54a9-410b-8618-afd741ddbba1">

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC-EXT contributor
- [ ] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by anshika013** [comment]
> @anshika013, please complete as soon as possible.

I'm unable to find the main website file
