### ISSUE TITLE
[Feature Request]: Nutrition Tracking

### ISSUE THREAD

**Issue by meghanakn473** [Open-Code-Crafters/FitFlex#76]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

IT allows users to log their meals by entering food items, portion sizes, and meal types through a user-friendly interface. Once logged, the application fetches nutritional information from a database or API, calculates total calories and macronutrients, and updates the user's daily intake on their dashboard. Users can review their meal history, edit or delete entries, and receive notifications if they approach their caloric goals. This feature promotes healthier eating habits by providing users with insights into their nutrition and helping them stay aligned with their dietary goals.

### Use Case

Sarah, a 28-year-old fitness enthusiast aiming to lose 10 pounds, uses the app's nutrition tracking feature to log her meals and receive instant nutritional information. The app sends reminders, provides visual insights into her eating habits, and connects her with a supportive community. This feature empowers Sarah to make informed dietary choices and enhances her accountability, increasing her chances of achieving her weight loss goal before her beach vacation.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC-EXT contributor
- [X] I'm a HACKTOBERFEST contributor
- [X] I have starred the repository

**Comment by meghanakn473** [comment]
@Sami3160 please assign me this issue i want to work on it

**Comment by jeevan10017** [comment]
@meghanakn473 go ahead 👍

**Comment by meghanakn473** [comment]
hey @jeevan10017 i have almost implemented the feature....im not able to fetch the meal data from the api...
could u guide me on next steps..

im getting like this

![WhatsApp Image 2024-10-06 at 20 01 07_2600ec77](https://github.com/user-attachments/assets/d7a27f82-f572-4d35-b0b7-47b51aba80c7)

**Comment by jeevan10017** [comment]
@GAVINESHWAR

**Comment by jeevan10017** [comment]
> hey @jeevan10017 i have almost implemented the feature....im not able to fetch the meal data from the api...
> could u guide me on next steps..
> 
> im getting like this
> 
> ![WhatsApp Image 2024-10-06 at 20 01 07_2600ec77](https://github.com/user-attachments/assets/d7a27f82-f572-4d35-b0b7-47b51aba80c7)
> 

@GAVINESHWAR

**Comment by meghanakn473** [comment]
> > hey @jeevan10017 i have almost implemented the feature....im not able to fetch the meal data from the api...
> > could u guide me on next steps..
> > im getting like this
> > ![WhatsApp Image 2024-10-06 at 20 01 07_2600ec77](https://private-user-images.githubusercontent.com/165137755/373954821-d7a27f82-f572-4d35-b0b7-47b51aba80c7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMjc0MDAsIm5iZiI6MTcyODIyNzEwMCwicGF0aCI6Ii8xNjUxMzc3NTUvMzczOTU0ODIxLWQ3YTI3ZjgyLWY1NzItNGQzNS1iMGI3LTQ3YjUxYWJhODBjNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNlQxNTA1MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZmRkNzdmNGI3ODNlZWE4NmI4MzhiNzE2OTI2YWVkNGFjY2U3MTY3NjZhODE2NjA2NjQzZmYwYmI4ZTgxZWQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0YtnpTbc4Lo7uZqhP3P_xPIUYTzkHhDglUPeo25a954)
> 
> @GAVINESHWAR

??

**Comment by jeevan10017** [comment]
He is the mentor of this repository under Gssoc-24 ext

**Comment by meghanakn473** [comment]
> hey @jeevan10017 i have almost implemented the feature....im not able to fetch the meal data from the api... could u guide me on next steps..
> 
> im getting like this
> 
> ![WhatsApp Image 2024-10-06 at 20 01 07_2600ec77](https://private-user-images.githubusercontent.com/165137755/373954821-d7a27f82-f572-4d35-b0b7-47b51aba80c7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMzM0MjIsIm5iZiI6MTcyODIzMzEyMiwicGF0aCI6Ii8xNjUxMzc3NTUvMzczOTU0ODIxLWQ3YTI3ZjgyLWY1NzItNGQzNS1iMGI3LTQ3YjUxYWJhODBjNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNlQxNjQ1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjA0NGM0OTkxNDc0M2FjMDdkM2I1MTAzMGI2MDEzZWNiMzQ5ODMzNzkyYzlhMDIyYmU1YjdhMjkyMmFlYTBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.eAoNi2Q6C_iW20Pp4iX1ziQvqg2y_2nSreL-J4zag-8)

@GAVINESHWAR please suggest me wt i can do with

**Comment by GAVINESHWAR** [comment]
> > hey @jeevan10017 i have almost implemented the feature....im not able to fetch the meal data from the api... could u guide me on next steps..
> > im getting like this
> > ![WhatsApp Image 2024-10-06 at 20 01 07_2600ec77](https://private-user-images.githubusercontent.com/165137755/373954821-d7a27f82-f572-4d35-b0b7-47b51aba80c7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMzM0MjIsIm5iZiI6MTcyODIzMzEyMiwicGF0aCI6Ii8xNjUxMzc3NTUvMzczOTU0ODIxLWQ3YTI3ZjgyLWY1NzItNGQzNS1iMGI3LTQ3YjUxYWJhODBjNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNlQxNjQ1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjA0NGM0OTkxNDc0M2FjMDdkM2I1MTAzMGI2MDEzZWNiMzQ5ODMzNzkyYzlhMDIyYmU1YjdhMjkyMmFlYTBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.eAoNi2Q6C_iW20Pp4iX1ziQvqg2y_2nSreL-J4zag-8)
> 
> @GAVINESHWAR please suggest me wt i can do with

@meghanakn473 I am unable to view the photo you send in the comment could you please send once again

**Comment by meghanakn473** [comment]
> > > hey @jeevan10017 i have almost implemented the feature....im not able to fetch the meal data from the api... could u guide me on next steps..
> > > im getting like this
> > > ![WhatsApp Image 2024-10-06 at 20 01 07_2600ec77](https://private-user-images.githubusercontent.com/165137755/373954821-d7a27f82-f572-4d35-b0b7-47b51aba80c7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMzM0MjIsIm5iZiI6MTcyODIzMzEyMiwicGF0aCI6Ii8xNjUxMzc3NTUvMzczOTU0ODIxLWQ3YTI3ZjgyLWY1NzItNGQzNS1iMGI3LTQ3YjUxYWJhODBjNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNlQxNjQ1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjA0NGM0OTkxNDc0M2FjMDdkM2I1MTAzMGI2MDEzZWNiMzQ5ODMzNzkyYzlhMDIyYmU1YjdhMjkyMmFlYTBjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.eAoNi2Q6C_iW20Pp4iX1ziQvqg2y_2nSreL-J4zag-8)
> > 
> > 
> > @GAVINESHWAR please suggest me wt i can do with
> 
> @meghanakn473 I am unable to view the photo you send in the comment could you please send once again

![WhatsApp Image 2024-10-06 at 20 01 07_2600ec77](https://github.com/user-attachments/assets/462dc91a-7fb0-42ce-9451-1fb3816c96b9)

**Comment by GAVINESHWAR** [comment]
@meghanakn473 , please check the api is working correctly or not and see the whether the syntax of the code is correct or not 


async function getData() {
  try {
    const response = await fetch('https://api.example.com/data'); // Make the API call
    const data = await response.json(); // Wait for the response to be converted to JSON
    console.log(data);  // Handle the data from the API
  } catch (error) {
    console.error('Error:', error);  // Handle any errors
  }
}

getData();  // Call the async function


this is the general syntax for getting the data from the external API


Please go through my repository where i used api for fetching data .

https://github.com/GAVINESHWAR/Photos_Search_Engine/blob/main/script.js

I hope this will help you

**Comment by meghanakn473** [comment]
> @meghanakn473 , please check the api is working correctly or not and see the whether the syntax of the code is correct or not
> 
> async function getData() { try { const response = await fetch('https://api.example.com/data'); // Make the API call const data = await response.json(); // Wait for the response to be converted to JSON console.log(data); // Handle the data from the API } catch (error) { console.error('Error:', error); // Handle any errors } }
> 
> getData(); // Call the async function
> 
> this is the general syntax for getting the data from the external API
> 
> Please go through my repository where i used api for fetching data .
> 
> https://github.com/GAVINESHWAR/Photos_Search_Engine/blob/main/script.js
> 
> I hope this will help you


this is my data fetching function from nutritionix.com

const API_URL = 'https://trackapi.nutritionix.com/v2/natural/nutrients';

export const fetchNutritionData = async (foodItem) => {
    try {
        const response = await axios.post(API_URL, 
            { query: foodItem },
            {
                headers: {
                    'x-app-id': APP_ID,
                    'x-app-key': API_KEY,
                    'Content-Type': 'application/json',
                }
            }
        );
        return response.data.foods; // Return array of foods with nutrition data
    } catch (error) {
        console.error('Error fetching data:', error);
        return null;
    }
};

please guide me if smtg is wrong @GAVINESHWAR

**Comment by GAVINESHWAR** [comment]
@meghanakn473  please check weather you the access key entered correctly or not , please check weather you have the access to fetch the data. Fo getting the data from the external api you should have the access for that you need the access key which given when you login to the Platform where your fetching data .

**Comment by meghanakn473** [comment]
> @meghanakn473  please check weather you the access key entered correctly or not , please check weather you have the access to fetch the data. Fo getting the data from the external api you should have the access for that you need the access key which given when you login to the Platform where your fetching data .


Yes sir I'm having access to Fetch data and also crossed the api key 
Everything is correct

**Comment by GAVINESHWAR** [comment]
> > @meghanakn473  please check weather you the access key entered correctly or not , please check weather you have the access to fetch the data. Fo getting the data from the external api you should have the access for that you need the access key which given when you login to the Platform where your fetching data .
> 
> Yes sir I'm having access to Fetch data and also crossed checked the api key Everything is correct
@meghanakn473 
Please send me complete api code of it , because the code you mention above I didn't observe any access key it it

**Comment by meghanakn473** [comment]
i hv put the api id and api key in .env file.

REACT_APP_NUTRITIONIX_APP_ID='466e8d9a'
REACT_APP_NUTRITIONIX_API_KEY='
b1975484d742bede95d2098e323b2bba'


and fetched it in this way 

import axios from 'axios';

// Replace with your Nutritionix App ID and API Key

const APP_ID = process.env.REACT_APP_NUTRITIONIX_APP_ID;
const API_KEY = process.env.REACT_APP_NUTRITIONIX_API_KEY;


const API_URL = 'https://trackapi.nutritionix.com/v2/natural/nutrients';

export const fetchNutritionData = async (foodItem) => {
    try {
        const response = await axios.post(API_URL, 
            { query: foodItem },
            {
                headers: {
                    'x-app-id': APP_ID,
                    'x-app-key': API_KEY,
                    'Content-Type': 'application/json',
                }
            }
        );
        return response.data.foods; // Return array of foods with nutrition data
    } catch (error) {
        console.error('Error fetching data:', error);
        return null;
    }
};

@GAVINESHWAR please check and review

**Comment by GAVINESHWAR** [comment]
import axios from 'axios';

const APP_ID = process.env.REACT_APP_NUTRITIONIX_APP_ID;
const API_KEY = process.env.REACT_APP_NUTRITIONIX_API_KEY;


const API_URL = 'https://trackapi.nutritionix.com/v2/natural/nutrients';

export const fetchNutritionData = async (foodItem) => {
  try {
    // Make POST request to Nutritionix API
    const response = await axios.post(
      API_URL,
      { query: foodItem }, // Send the food item as 'query'
      {
        headers: {
          'x-app-id': APP_ID,      // Nutritionix App ID from env
          'x-app-key': API_KEY,    // Nutritionix API Key from env
          'Content-Type': 'application/json', // Specify JSON format
        },
      }
    );

    return response.data.foods;
  } catch (error) {
    console.error('Error fetching data:', error);
    return null; 
  }
};


@meghanakn473 , please go through this code i hope this will work

**Comment by meghanakn473** [comment]
Sure I'll check and update

**Comment by meghanakn473** [comment]
> import axios from 'axios';
> 
> const APP_ID = process.env.REACT_APP_NUTRITIONIX_APP_ID; const API_KEY = process.env.REACT_APP_NUTRITIONIX_API_KEY;
> 
> const API_URL = 'https://trackapi.nutritionix.com/v2/natural/nutrients';
> 
> export const fetchNutritionData = async (foodItem) => { try { // Make POST request to Nutritionix API const response = await axios.post( API_URL, { query: foodItem }, // Send the food item as 'query' { headers: { 'x-app-id': APP_ID, // Nutritionix App ID from env 'x-app-key': API_KEY, // Nutritionix API Key from env 'Content-Type': 'application/json', // Specify JSON format }, } );
> 
> ```
> return response.data.foods;
> ```
> 
> } catch (error) { console.error('Error fetching data:', error); return null; } };
> 
> @meghanakn473 , please go through this code i hope this will work

tried it, but the result is same ntg changed @GAVINESHWAR

**Comment by meghanakn473** [comment]
hey it worked, so shd i dispose api keys directly in file or keep it in .env

**Comment by GAVINESHWAR** [comment]
> @GAVINESHWAR hey it worked, so shd i add api keys directly in file or keep it in .env
Ok @meghanakn473
